```{r}
library(gmodels)
library(vcd)
#install.packages("smbinning")
library(smbinning)
library(dplyr)
library(stringr)
#install.packages("shades")
library(shades)
library(latticeExtra)

accepted <- read.csv("accepted_customers.csv")
rejected <- read.csv("rejected_customers.csv")
```

```{r}
factor <- c(
  "BUREAU", "CAR", "CARDS", "DIV", "EC_CARD", "FINLOAN", "LOCATION",
  "NAT", "PRODUCT", "PROF", "REGN", "RESID", "TEL", "NMBLOAN"
)

accepted$good <- abs(accepted$GB - 1)
table(accepted$good)

#make this example reproducible
# Create Training and Validation #
set.seed(12345)
train_id <- sample(seq_len(nrow(accepted)), size = floor(0.7*nrow(accepted)))

train <- accepted[train_id, ]
test <- accepted[-train_id, ]

for (col in factor) {train[, col] <- as.factor(train[, col])}
for (col in factor) {test[, col] <- as.factor(test[, col])}

#Check missing values
sapply(train, function(x) sum(is.na(x)))

#####################
# SEPARATION CHECKS #
#####################

#for (col in factor) {
#  print(col)
#  print(table(train[[col]], train$GB))
#  }


#BUREAU column
train$BUREAU <- as.character(train$BUREAU)
train$BUREAU[train$BUREAU == "2"] <- "2+"
train$BUREAU[train$BUREAU == "3"] <- "2+"

#CARDS
train$CARDS <- as.character(train$CARDS)
train$CARDS[train$CARDS == "American Express"] <- "Other credit car"
train$CARDS[train$CARDS == "VISA Others"] <- "VISA"
train$CARDS[train$CARDS == "VISA mybank"] <- "VISA"

#PRODUCT
train$PRODUCT <- as.character(train$PRODUCT)
train$PRODUCT[train$PRODUCT == ""] <- "Others"

#PROF
train$PROF <- as.character(train$PROF)
train$PROF[train$PROF == ""] <- "Others"

#TEL
train$TEL <- as.character(train$TEL)
train$TEL[train$TEL == "0"] <- "0 or 1"
train$TEL[train$TEL == "1"] <- "0 or 1"

#BUREAU column
test$BUREAU <- as.character(test$BUREAU)
test$BUREAU[test$BUREAU == "2"] <- "2+"
test$BUREAU[test$BUREAU == "3"] <- "2+"

#CARDS
test$CARDS <- as.character(test$CARDS)
test$CARDS[test$CARDS == "American Express"] <- "Other credit car"
test$CARDS[test$CARDS == "VISA Others"] <- "VISA"
test$CARDS[test$CARDS == "VISA mybank"] <- "VISA"

#PRODUCT
test$PRODUCT <- as.character(test$PRODUCT)
test$PRODUCT[test$PRODUCT == ""] <- "Others"

#PROF
test$PROF <- as.character(test$PROF)
test$PROF[test$PROF == ""] <- "Others"

#TEL
test$TEL <- as.character(test$TEL)
test$TEL[test$TEL == "0"] <- "0 or 1"
test$TEL[test$TEL == "1"] <- "0 or 1"

# Change categorical variables to factors
for (col in factor) {train[, col] <- as.factor(train[, col])}

for (col in factor) {test[, col] <- as.factor(test[, col])}
```

```{r}
## LOOP for Binning

# Information Value for Each Variable #
iv_summary <- smbinning.sumiv(df = train, y = "good")

smbinning.sumiv.plot(iv_summary)
iv_summary # Only Continuous Variables >= 0.1 IV #

# Binning of Continuous Variables - IV >= 0.1 #
num_names <- names(train)[sapply(train, is.numeric)] # Gathering the names of numeric variables in data #

result_all_sig <- list() # Creating empty list to store all results #

for(i in 1:length(num_names)){
  check_res <- smbinning(df = train, y = "good", x = num_names[i])
  
  if(length(check_res) == 1) {     #This is to handle "NO Significant Splits"
    next
  }else if (check_res$iv) {
    if (check_res$iv < 0.1) {
      next
    } else {
      result_all_sig[[num_names[i]]] <- check_res
    }
  } else {
    next
  }
}

for(i in 1:length(factor)){
  check_res <- smbinning.factor(df = train, y = "good", x = factor[i])
  
  if(length(check_res) == 1) {     #This is to handle "NO Significant Splits"
    next
  }else if (check_res$iv) {
    #print(factors[i],check_res$iv)
    if (check_res$iv < 0.1) {
      next
    } else {
      result_all_sig[[factor[i]]] <- check_res
    }
  } else {
    next
  }
}

# Generating Variables of Bins and WOE Values #
for(i in 1:4) {
  train <- smbinning.gen(df = train, ivout = result_all_sig[[i]], chrname = paste(result_all_sig[[i]]$x, "_bin", sep = ""))
}

for(i in 5:6) {
  train <- smbinning.factor.gen(df = train, ivout = result_all_sig[[i]], chrname = paste(result_all_sig[[i]]$x, "_bin", sep = ""))
}


```

```{r}
for (j in 1:length(result_all_sig)) {
  for (i in 1:nrow(train)) {
    bin_name <- paste(result_all_sig[[j]]$x, "_bin", sep = "")
    bin <- substr(train[[bin_name]][i], 2, 2)
    
    woe_name <- paste(result_all_sig[[j]]$x, "_WOE", sep = "")
    
    if(bin == 0) {
      bin <- dim(result_all_sig[[j]]$ivtable)[1] - 1
      train[[woe_name]][i] <- result_all_sig[[j]]$ivtable[bin, "WoE"]
    } else {
      train[[woe_name]][i] <- result_all_sig[[j]]$ivtable[bin, "WoE"]
    }
  }
}
```

```{r # MODEL BUILDING #}
# Build Initial Logistic Regression #
initial_score <- glm(data = train, GB ~ PERS_H_WOE +
                       AGE_WOE +
                       TMJOB1_WOE +
                       INCOME_WOE +
                       CARDS_WOE +
                       EC_CARD_WOE, 
                     weights = train$X_freq_, family = "binomial")

summary(initial_score)
```
```{r # MODEL EVALUATION #TRAINING DATA}
# Evaluate the Initial Model - Training Data #
train$pred <- initial_score$fitted.values

smbinning.metrics(dataset = train, prediction = "pred", actualclass = "GB", report = 1)
```
```{r  MODEL EVALUATION #TRAINING DATA}
#Evaluate the Initial Model - Testing Data #
for(i in 1:4) {
  test <- smbinning.gen(df = test, ivout = result_all_sig[[i]], chrname = paste(result_all_sig[[i]]$x, "_bin", sep = ""))
}

for(i in 5:6) {
  test <- smbinning.factor.gen(df = test, ivout = result_all_sig[[i]], chrname = paste(result_all_sig[[i]]$x, "_bin", sep = ""))
}

for (j in 1:length(result_all_sig)) {
  for (i in 1:nrow(test)) {
    bin_name <- paste(result_all_sig[[j]]$x, "_bin", sep = "")
    bin <- substr(test[[bin_name]][i], 2, 2)
    
    woe_name <- paste(result_all_sig[[j]]$x, "_WOE", sep = "")
    
    if(bin == 0) {
      bin <- dim(result_all_sig[[j]]$ivtable)[1] - 1
      test[[woe_name]][i] <- result_all_sig[[j]]$ivtable[bin, "WoE"]
    } else {
      test[[woe_name]][i] <- result_all_sig[[j]]$ivtable[bin, "WoE"]
    }
  }
}

test$pred <- predict(initial_score, newdata=test, type='response')

smbinning.metrics(dataset = test, prediction = "pred", actualclass = "GB", report = 1)
```
```{r}
smbinning.metrics(dataset = test, prediction = "pred", actualclass = "GB", report = 0, plot = "ks")

smbinning.metrics(dataset = test, prediction = "pred", actualclass = "GB", report = 0, plot = "auc")
```

```{r}
# Add Scores to Initial Model #
pdo <- 50
score <- 500
odds <- 20
fact <- pdo/log(2)
os <- score - fact*log(odds)
var_names <- names(initial_score$coefficients[-1])

# Train Data

for(i in var_names) {
  beta <- initial_score$coefficients[i]
  beta0 <- initial_score$coefficients["(Intercept)"]
  nvar <- length(var_names)
  WOE_var <- train[[i]]
  points_name <- paste(str_sub(i, end = -4), "points", sep="")
  
  train[[points_name]] <- -(WOE_var*(beta) + (beta0/nvar))*fact + os/nvar
}

colini <- (ncol(train)-nvar + 1)
colend <- ncol(train)
train$Score <- rowSums(train[, colini:colend])

hist(train$Score, breaks = 50, xlim = c(400,700), main = "Distribution of Train Scores", xlab = "Score")

# Test Data

for(i in var_names) {
  beta <- initial_score$coefficients[i]
  beta0 <- initial_score$coefficients["(Intercept)"]
  nvar <- length(var_names)
  WOE_var <- test[[i]]
  points_name <- paste(str_sub(i, end = -4), "points", sep="")
  
  test[[points_name]] <- -(WOE_var*(beta) + (beta0/nvar))*fact + os/nvar
}

colini <- (ncol(test)-nvar + 1)
colend <- ncol(test)
test$Score <- rowSums(test[, colini:colend])

hist(test$Score, breaks = 50, xlim = c(400,700), main = "Distribution of Test Scores", xlab = "Score")

accepts_scored <- rbind(train, test)
hist(accepts_scored$Score, breaks = 50, xlim = c(400,700), main = "Distribution of Scores", xlab = "Score")

```
```{r}

```


```{r}
# Plotting Default by Score in Train Data #
cutpoints <- quantile(train$Score, probs = seq(0,1,0.10))
train$Score.QBin <- cut(train$Score, breaks=cutpoints, include.lowest=TRUE)
Default.QBin.train <- round(table(train$Score.QBin, train$GB)[,2]/rowSums(table(train$Score.QBin, train$GB))*100,2)

print(Default.QBin.train)

Default.QBin.train.pop <- round(table(train$Score.QBin, train$GB)[,2]/(table(train$Score.QBin, train$GB)[,2] + table(train$Score.QBin, train$GB)[,1]*4.75)*100,2)

print(Default.QBin.train.pop)

# Plotting Default by Score in Test Data #
cutpoints <- quantile(test$Score, probs = seq(0,1,0.10))
test$Score.QBin <- cut(test$Score, breaks=cutpoints, include.lowest=TRUE)
Default.QBin.test <- round(table(test$Score.QBin, test$GB)[,2]/rowSums(table(test$Score.QBin, test$GB))*100,2)

print(Default.QBin.test)

barplot(Default.QBin.test, 
        main = "Default Decile Plot", 
        xlab = "Deciles of Scorecard",
        ylab = "Default Rate (%)", ylim = c(0,60),
        col = saturation(heat.colors, scalefac(0.8))(10))
abline(h = 20.5, lwd = 2, lty = "dashed")
text(11.5, 23, "Current = 20.5%")
```

